/**
 * Generated by packages/sim/scripts/calibrate-rating.ts: Stockfish's average loss per move at each UCI_Elo
 * setting, smoothed (log-linear fit). Raw measurements are in reports/rating-calibration.md.
 */
export const RATING_CURVE: readonly { elo: number; meanLoss: number }[] = [
  {
    "elo": 1320,
    "meanLoss": 12.02
  },
  {
    "elo": 1600,
    "meanLoss": 9.3
  },
  {
    "elo": 1900,
    "meanLoss": 7.06
  },
  {
    "elo": 2200,
    "meanLoss": 5.37
  },
  {
    "elo": 2500,
    "meanLoss": 4.08
  },
  {
    "elo": 2800,
    "meanLoss": 3.1
  },
  {
    "elo": 3190,
    "meanLoss": 2.17
  }
];
